export default {
  "login": "meet21",
  "id": 54228011,
  "node_id": "MDQ6VXNlcjU0MjI4MDEx",
  "avatar_url": "https://avatars.githubusercontent.com/u/54228011?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/meet21",
  "html_url": "https://github.com/meet21",
  "followers_url": "https://api.github.com/users/meet21/followers",
  "following_url": "https://api.github.com/users/meet21/following{/other_user}",
  "gists_url": "https://api.github.com/users/meet21/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/meet21/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/meet21/subscriptions",
  "organizations_url": "https://api.github.com/users/meet21/orgs",
  "repos_url": "https://api.github.com/users/meet21/repos",
  "events_url": "https://api.github.com/users/meet21/events{/privacy}",
  "received_events_url": "https://api.github.com/users/meet21/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Meet Bhalgamiya",
  "company": 'Student',
  "blog": "none",
  "location": 'Mumbai',
  "email": 'meet21bhalgamiya@gmail.com',
  "hireable": null,
  "bio": 'I Transform Ideas Into Products',
  "twitter_username": 'Meet Bhalgamiya',
  "public_repos": 5,
  "public_gists": 100,
  "followers": 196,
  "following": 20,
  "created_at": "2019-08-18T05:22:11Z",
  "updated_at": "2021-03-16T09:20:51Z"
};
